In [1]:
import pandas as pd
data =pd.read_csv("Student-University.csv", index_col=False, header=None)
data

0          1  2
0   34.623660  78.024693  0
1   30.286711  43.894998  0
2   35.847409  72.902198  0
3   60.182599  86.308552  1
4   79.032736  75.344376  1
..        ...        ... ..
95  83.489163  48.380286  1
96  42.261701  87.103851  1
97  99.315009  68.775409  1
98  55.340018  64.931938  1
99  74.775893  89.529813  1

[100 rows x 3 columns]

In [2]:
# data.drop(labels=0, axis=0, inplace = True)

In [3]:
data.head()

0          1  2
0  34.623660  78.024693  0
1  30.286711  43.894998  0
2  35.847409  72.902198  0
3  60.182599  86.308552  1
4  79.032736  75.344376  1

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X=data.iloc[:,0:2]
print(X)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)
print(scaler)
print(scaler.mean_)
X = scaler.transform(X)

            0          1
0   34.623660  78.024693
1   30.286711  43.894998
2   35.847409  72.902198
3   60.182599  86.308552
4   79.032736  75.344376
..        ...        ...
95  83.489163  48.380286
96  42.261701  87.103851
97  99.315009  68.775409
98  55.340018  64.931938
99  74.775893  89.529813

[100 rows x 2 columns]
StandardScaler()
[65.64427406 66.22199809]


In [6]:
y = data.iloc[:,-1]
y

0     0
1     0
2     0
3     1
4     1
     ..
95    1
96    1
97    1
98    1
99    1
Name: 2, Length: 100, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [8]:
X_train.size

160

In [9]:
X_train = pd.DataFrame(X_train)
X_test = pd.DataFrame(X_test)
X_train

0         1
0  -1.568031 -1.038500
1  -0.829392 -0.346846
2  -0.949347  1.203586
3   0.856498 -1.271097
4   0.860650  0.554904
..       ...       ...
75 -0.075787  0.794286
76  0.145875  1.047739
77 -0.793246 -0.887928
78 -1.707949  1.588812
79 -1.300921  1.693554

[80 rows x 2 columns]

In [10]:
y_train

61    0
55    0
76    1
79    0
12    1
     ..
37    1
85    1
54    0
57    0
66    1
Name: 2, Length: 80, dtype: int64

In [11]:
x1 = X_train[0].values
x1

array([-1.56803122, -0.82939191, -0.94934675,  0.8564979 ,  0.86065022,
        0.31776703, -0.17672918,  1.28623744,  0.73863826, -1.34839922,
        0.08651467,  0.69152826,  1.28116721, -0.78437891,  0.44442728,
       -1.82625564, -0.19700066, -1.38726847, -1.60736862, -1.62497511,
       -1.63882482, -1.83802631, -0.56863523, -0.68676645, -0.52488391,
       -1.31231814,  0.86383711, -0.35139858,  0.67100669,  1.41886056,
        0.63426559,  0.97044832, -0.1844568 , -0.53222578,  0.59650575,
        1.46947562,  0.53998666,  1.65290418, -1.70042734, -1.06199728,
       -0.60293429,  0.50366692, -1.60224763, -0.72810195,  0.34617678,
       -1.62350714, -1.08343328, -1.21735452,  1.73693492,  1.48750373,
        1.56075461,  0.75592876,  0.1921582 , -0.69916396,  0.75131151,
        0.50790698,  1.02063763, -0.43415649, -0.22029098, -1.53903969,
       -0.78042096,  1.65941042, -0.23437234,  1.25003483,  0.58543944,
       -1.2077347 , -0.85594644,  0.11893077,  0.92170742,  0.48

In [12]:
x2 = X_train[1].values
x2

array([-1.03849986, -0.34684551,  1.20358601, -1.27109695,  0.55490359,
        0.66153625, -0.76588887, -1.23482132,  0.42949041,  0.53082781,
        0.01986816,  0.49337794,  1.15128248,  0.51855329,  0.19484284,
       -1.2075414 , -0.86350486, -0.06632457, -0.31507682,  0.48760951,
        1.76571557, -0.89937003, -0.7576197 , -0.29489455, -1.65775547,
        0.26748769, -1.38476189,  0.52118118,  1.64553968, -1.4830648 ,
        0.14875155, -1.22709853,  1.65210535, -0.06977207,  0.22911224,
        0.59152637,  1.14651105,  0.14275969, -1.23933351, -0.5357394 ,
        1.24314792,  1.05669679,  0.63834112, -1.0473818 ,  1.62283321,
       -1.19053019,  0.012336  ,  0.68269533, -0.2824808 , -0.03532122,
       -1.51418452,  1.40046365,  1.70347834, -0.16735724, -1.15742514,
        1.30897879, -0.49595429, -0.36278249,  0.35619356,  0.3612943 ,
       -0.93923898,  1.10904426,  1.63818413, -1.12840052, -1.00845873,
        1.12938152, -0.77550399, -1.05699346, -0.96495748, -1.06

In [13]:
b0 = 0
b1 = 0
b2 = 0
import numpy as np

In [14]:
x1

array([-1.56803122, -0.82939191, -0.94934675,  0.8564979 ,  0.86065022,
        0.31776703, -0.17672918,  1.28623744,  0.73863826, -1.34839922,
        0.08651467,  0.69152826,  1.28116721, -0.78437891,  0.44442728,
       -1.82625564, -0.19700066, -1.38726847, -1.60736862, -1.62497511,
       -1.63882482, -1.83802631, -0.56863523, -0.68676645, -0.52488391,
       -1.31231814,  0.86383711, -0.35139858,  0.67100669,  1.41886056,
        0.63426559,  0.97044832, -0.1844568 , -0.53222578,  0.59650575,
        1.46947562,  0.53998666,  1.65290418, -1.70042734, -1.06199728,
       -0.60293429,  0.50366692, -1.60224763, -0.72810195,  0.34617678,
       -1.62350714, -1.08343328, -1.21735452,  1.73693492,  1.48750373,
        1.56075461,  0.75592876,  0.1921582 , -0.69916396,  0.75131151,
        0.50790698,  1.02063763, -0.43415649, -0.22029098, -1.53903969,
       -0.78042096,  1.65941042, -0.23437234,  1.25003483,  0.58543944,
       -1.2077347 , -0.85594644,  0.11893077,  0.92170742,  0.48

In [15]:
for j in zip(x1,x2):
    print(j[0],j[1])

-1.5680312216636227 -1.0384998644994903
-0.8293919051726506 -0.3468455091655328
-0.9493467468838972 1.2035860147950017
0.8564979005434388 -1.2710969522222555
0.8606502217495229 0.5549035900150964
0.31776703448634325 0.6615362454736213
-0.17672918056252784 -0.7658888682721517
1.2862374368325227 -1.2348213174853204
0.738638256724844 0.4294904130693311
-1.3483992229035093 0.5308278073477496
0.08651466949941705 0.019868162799294483
0.6915282598765105 0.49337793963040477
1.2811672065530657 1.151282483387623
-0.7843789057399158 0.5185532918275333
0.44442727884827443 0.19484284091973614
-1.8262556392310556 -1.207541401375004
-0.19700065883348278 -0.8635048566112424
-1.3872684712510013 -0.0663245696268831
-1.6073686161122662 -0.3150768209950575
-1.6249751103996153 0.48760951336711683
-1.6388248216202954 1.7657155734977112
-1.838026312626371 -0.8993700316649655
-0.5686352282526221 -0.7576196988452815
-0.6867664492150503 -0.29489455203902126
-0.5248839087573258 -1.6577554671560284
-1.31231813702

In [16]:
for j in range(0,80):
    print(x1[j],x2[j])

-1.5680312216636227 -1.0384998644994903
-0.8293919051726506 -0.3468455091655328
-0.9493467468838972 1.2035860147950017
0.8564979005434388 -1.2710969522222555
0.8606502217495229 0.5549035900150964
0.31776703448634325 0.6615362454736213
-0.17672918056252784 -0.7658888682721517
1.2862374368325227 -1.2348213174853204
0.738638256724844 0.4294904130693311
-1.3483992229035093 0.5308278073477496
0.08651466949941705 0.019868162799294483
0.6915282598765105 0.49337793963040477
1.2811672065530657 1.151282483387623
-0.7843789057399158 0.5185532918275333
0.44442727884827443 0.19484284091973614
-1.8262556392310556 -1.207541401375004
-0.19700065883348278 -0.8635048566112424
-1.3872684712510013 -0.0663245696268831
-1.6073686161122662 -0.3150768209950575
-1.6249751103996153 0.48760951336711683
-1.6388248216202954 1.7657155734977112
-1.838026312626371 -0.8993700316649655
-0.5686352282526221 -0.7576196988452815
-0.6867664492150503 -0.29489455203902126
-0.5248839087573258 -1.6577554671560284
-1.31231813702

In [17]:
y_train = np.array(y_train)
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1])

In [18]:
for j in range(0,80):
    print(x1[j],x2[j],y_train[j])

-1.5680312216636227 -1.0384998644994903 0
-0.8293919051726506 -0.3468455091655328 0
-0.9493467468838972 1.2035860147950017 1
0.8564979005434388 -1.2710969522222555 0
0.8606502217495229 0.5549035900150964 1
0.31776703448634325 0.6615362454736213 1
-0.17672918056252784 -0.7658888682721517 0
1.2862374368325227 -1.2348213174853204 1
0.738638256724844 0.4294904130693311 1
-1.3483992229035093 0.5308278073477496 0
0.08651466949941705 0.019868162799294483 1
0.6915282598765105 0.49337793963040477 1
1.2811672065530657 1.151282483387623 1
-0.7843789057399158 0.5185532918275333 1
0.44442727884827443 0.19484284091973614 1
-1.8262556392310556 -1.207541401375004 0
-0.19700065883348278 -0.8635048566112424 0
-1.3872684712510013 -0.0663245696268831 0
-1.6073686161122662 -0.3150768209950575 0
-1.6249751103996153 0.48760951336711683 0
-1.6388248216202954 1.7657155734977112 0
-1.838026312626371 -0.8993700316649655 0
-0.5686352282526221 -0.7576196988452815 0
-0.6867664492150503 -0.29489455203902126 0
-0.524

Schotisitc gradient decent: for each row tune the parameters(b0,b1,b2) 
gradient decent: for entire row tune the parameters
b0 = b0 - (alpha)*Db0
b1 = b1 - (alpha)*Db1
Db0 = -2*sum((y-y_pred)*y_pred*(1-y_pred))
Db1 = -2*sum((y-y_pred)*y_pred*(1-y_pred))*x1
.
.
.

In [19]:
#schotistic gradient
# for i in range(0,15000):
#     for j in range(0,80):
#         yprd = b0 + b1*x1[j] + b2*x2[j]
#         # yprd
#         pred = 1 / (1+ np.exp(-yprd))
#         # np.round(pred)
#         b0 = b0 + 0.01*(y_train[j]-pred)*pred*(1-pred)*1
#         b1 = b1 + 0.01*(y_train[j]-pred)*pred*(1-pred)*x1[j]
#         b2 = b2 + 0.01*(y_train[j]-pred)*pred*(1-pred)*x2[j]
        


In [20]:
#gradient decent
for i in range(0,10000):
    yprd = b0 + b1*x1 + b2*x2
    # yprd
    pred = 1 / (1+ np.exp(-yprd))
    # np.round(pred)
    D_b0 = -2 * sum((y_train - pred) * pred * (1 - pred))  
    D_b1 = -2 * sum(x1 * (y_train - pred) * pred * (1 - pred))  
    D_b2 = -2 * sum(x2 * (y_train - pred) * pred * (1 - pred))  
    # Update b0 and b1
    b0 = b0 - 0.01 * D_b0
    b1 = b1 - 0.01 * D_b1


In [21]:
pred = np.round(pred)
pred

array([0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0.])

In [22]:
print(b0,b1,b2)

1.1084336939261947 2.2901769857428755 0


In [23]:
y_train

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1])

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
X_test_1 =  X_test[0].values
X_test_2 =  X_test[1].values

In [26]:
yprd_test = b0 + b1*X_test_1 + b2*X_test_2
pred_test = 1 / (1+ np.exp(-yprd_test))

In [27]:
pred_test

array([0.81960596, 0.37749896, 0.62120357, 0.77151063, 0.97938688,
       0.71475342, 0.35019323, 0.89936546, 0.99424556, 0.98966007,
       0.8457857 , 0.99388786, 0.67027089, 0.98113201, 0.9633212 ,
       0.61357669, 0.78798295, 0.77536237, 0.90174262, 0.89922233])

In [28]:
print(accuracy_score(y_test,np.round(pred_test)))

0.7


In [29]:
for j in zip(y_test,np.round(pred_test)):
    print(j[0],j[1])

1 1.0
1 0.0
0 1.0
0 1.0
1 1.0
1 1.0
0 0.0
0 1.0
1 1.0
1 1.0
1 1.0
1 1.0
1 1.0
1 1.0
1 1.0
1 1.0
0 1.0
1 1.0
0 1.0
1 1.0
