In [2]:
import numpy as np
import pandas as pd
df=pd.read_csv("glass.csv")
df.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit_transform(df))

[[-1.72397593  0.87286765  0.28495326 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.70778837 -0.24933347  0.59181718 ... -0.35287683 -0.5864509
  -0.84827468]
 [-1.6916008  -0.72131806  0.14993314 ... -0.35287683 -0.5864509
  -0.84827468]
 ...
 [ 1.6916008   0.75404635  1.16872135 ...  2.95320036 -0.5864509
   2.01047778]
 [ 1.70778837 -0.61239854  1.19327046 ...  2.81208731 -0.5864509
   2.01047778]
 [ 1.72397593 -0.41436305  1.00915211 ...  3.01367739 -0.5864509
   2.01047778]]


In [4]:
x=df.drop('Type',axis=1)
y=df.Type

In [5]:
x.head()

Id       RI     Na    Mg    Al    Si      K    Ca   Ba   Fe
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0

In [6]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Type, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [8]:
from sklearn.svm import SVC
svclassifier=SVC(kernel='linear')

In [9]:
svclassifier.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [10]:
y_pred=svclassifier.predict(x_test)

In [11]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))

0.9846153846153847


In [12]:
print(svclassifier.support_vectors_)

[[7.00000e+01 1.52300e+00 1.33100e+01 3.58000e+00 8.20000e-01 7.19900e+01
  1.20000e-01 1.01700e+01 0.00000e+00 3.00000e-02]
 [1.46000e+02 1.51839e+00 1.28500e+01 3.67000e+00 1.24000e+00 7.25700e+01
  6.20000e-01 8.68000e+00 0.00000e+00 3.50000e-01]
 [7.30000e+01 1.51593e+00 1.30900e+01 3.59000e+00 1.52000e+00 7.31000e+01
  6.70000e-01 7.83000e+00 0.00000e+00 0.00000e+00]
 [7.10000e+01 1.51574e+00 1.48600e+01 3.67000e+00 1.74000e+00 7.18700e+01
  1.60000e-01 7.36000e+00 0.00000e+00 1.20000e-01]
 [1.62000e+02 1.51934e+00 1.36400e+01 3.54000e+00 7.50000e-01 7.26500e+01
  1.60000e-01 8.89000e+00 1.50000e-01 2.40000e-01]
 [1.48000e+02 1.51610e+00 1.33300e+01 3.53000e+00 1.34000e+00 7.26700e+01
  5.60000e-01 8.33000e+00 0.00000e+00 0.00000e+00]
 [1.75000e+02 1.52058e+00 1.28500e+01 1.61000e+00 2.17000e+00 7.21800e+01
  7.60000e-01 9.70000e+00 2.40000e-01 5.10000e-01]
 [1.65000e+02 1.51915e+00 1.27300e+01 1.85000e+00 1.86000e+00 7.26900e+01
  6.00000e-01 1.00900e+01 0.00000e+00 0.00000e+00]


In [13]:
print(svclassifier.n_support_)

[1 3 2 3 3 3]


In [14]:
print(confusion_matrix(y_test,y_pred))

[[20  0  0  0  0  0]
 [ 0 25  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  1  3  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0  6]]


In [15]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        25
           3       0.89      1.00      0.94         8
           5       1.00      0.75      0.86         4
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         6

    accuracy                           0.98        65
   macro avg       0.98      0.96      0.97        65
weighted avg       0.99      0.98      0.98        65



In [16]:
model1=SVC(kernel='sigmoid')
model2=SVC(kernel='poly')
model3=SVC(kernel='rbf')

In [17]:
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model3.fit(x_train,y_train)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [18]:
ypred1=model1.predict(x_test)
ypred2=model2.predict(x_test)
ypred3=model3.predict(x_test)

In [22]:
print(accuracy_score(y_test,ypred1))

0.38461538461538464


In [20]:
print(accuracy_score(y_test,ypred2))

0.9846153846153847


In [21]:
print(accuracy_score(y_test,ypred3))

0.9538461538461539


In [23]:
[{'kernel':['rbf'],'gamma':[1e-3,1e-4],
     'C':[1,10,100,1000]},
{'kernel':['linear'],'C':[1,10,100,1000]},
{'kernel':['poly'],'gamma':[1e-3,1e-4],'degree':[2,3,4]},
{'kernel':['sigmoid'],'C':[1,10,100,1000],'gamma':[1e-3,1e-4,1e-5]}]

[{'kernel': ['rbf'], 'gamma': [0.001, 0.0001], 'C': [1, 10, 100, 1000]},
 {'kernel': ['linear'], 'C': [1, 10, 100, 1000]},
 {'kernel': ['poly'], 'gamma': [0.001, 0.0001], 'degree': [2, 3, 4]},
 {'kernel': ['sigmoid'],
  'C': [1, 10, 100, 1000],
  'gamma': [0.001, 0.0001, 1e-05]}]

In [24]:
params_grid1=[{'kernel':['rbf']},
             {'kernel':['linear']},
             {'kernel':['poly']},
             {'kernel':['sigmoid']}]

In [25]:
from sklearn.model_selection import GridSearchCV
svm_model=GridSearchCV(SVC(),params_grid1,cv=5)
svm_model.fit(x_train,y_train)

C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\asus\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: 

GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid=[{'kernel': ['rbf']}, {'kernel': ['linear']},
                         {'kernel': ['poly']}, {'kernel': ['sigmoid']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [26]:
print('Best score for training data:',svm_model.best_score_,"\n")

#View the best parameters for the model found using grid search
print('Best C:',svm_model.best_estimator_.C,"\n")
print('Best Kernel:',svm_model.best_estimator_.kernel,"\n")
print('Best Gamma:',svm_model.best_estimator_.gamma,"\n")

final_model=svm_model.best_estimator_
Y_pred=final_model.predict(x_test)

Best score for training data: 0.9865771812080537 

Best C: 1.0 

Best Kernel: linear 

Best Gamma: auto_deprecated 



In [27]:
print(accuracy_score(y_test,Y_pred))

0.9846153846153847
