In [2]:
import numpy as np
import pandas as pd
from copy import deepcopy
data = pd.read_csv("kmeans.csv")
print(data)

    X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0


In [3]:
def euclidean(a,b, ax=1):
    return np.linalg.norm(a-b, axis=ax)

In [10]:
def main():
    k = 3
    X = pd.read_csv('kmeans.csv',index_col=False)
    print(X)

    x1 = X['X1'].values
    x2 = X['X2'].values
    X = np.array(list(zip(x1, x2)))
    print(X)
    C_x = [6.2, 6.6 ,6.5]
    C_y = [3.2, 3.7, 3.0]
    Centroid = np.array(list(zip(C_x, C_y)), dtype=np.float32)
    print("Initial Centroids")
    print(Centroid.shape)
    

    Centroid_old = np.zeros(Centroid.shape)
    print(Centroid_old)
    # Cluster Lables(0, 1, 2)
    clusters = np.zeros(len(X))
    print(clusters)
    error = euclidean(Centroid, Centroid_old, None)
    print(error)
    iterr = 0
    # Loop will run till the error becomes zero
    while error != 0:
        # Assigning each value to its closest cluster
        iterr = iterr + 1
        for i in range(len(X)):
            #print(X[i])
            distances = euclidean(X[i], Centroid)
            print("dist: ", distances)
            cluster = np.argmin(distances)
            print("clust: ", cluster)
            clusters[i] = cluster

        Centroid_old = deepcopy(Centroid)
        
        # Finding the new centroids by taking the Mean
        for p in range(k):
            points = [X[j] for j in range(len(X)) if clusters[j] == p]
            print("point: ",points)
            Centroid[p] = np.mean(points, axis=0)
        print(" Centre of the clusters after ", iterr," Iteration \n", Centroid)
        error = euclidean(Centroid, Centroid_old, None)
        print("Error  ... ",error)  
    

if __name__ == "__main__": 
    main()

    X1   X2
0  5.9  3.2
1  4.6  2.9
2  6.2  2.8
3  4.7  3.2
4  5.5  4.2
5  5.0  3.0
6  4.9  3.1
7  6.7  3.1
8  5.1  3.8
9  6.0  3.0
[[5.9 3.2]
 [4.6 2.9]
 [6.2 2.8]
 [4.7 3.2]
 [5.5 4.2]
 [5.  3. ]
 [4.9 3.1]
 [6.7 3.1]
 [5.1 3.8]
 [6.  3. ]]
Initial Centroids
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
12.537144692236463
dist:  [0.29999981 0.86023248 0.63245553]
clust:  0
dist:  [1.62788188 2.15406585 1.90262976]
clust:  0
dist:  [0.40000005 0.98488579 0.36055513]
clust:  2
dist:  [1.49999981 1.96468819 1.81107703]
clust:  0
dist:  [1.22065541 1.20830449 1.56204994]
clust:  1
dist:  [1.21655233 1.74642485 1.5       ]
clust:  0
dist:  [1.30384029 1.80277556 1.60312195]
clust:  0
dist:  [0.50990215 0.60827632 0.2236068 ]
clust:  2
dist:  [1.25299622 1.50332954 1.61245155]
clust:  0
dist:  [0.28284261 0.92195442 0.5       ]
clust:  0
point:  [array([5.9, 3.2]), array([4.6, 2.9]), array([4.7, 3.2]), array([5., 3.]), array([4.9, 3.1]), array([5.1, 3.8]), array([6., 3

NameError: name 'x1' is not defined